Wajid
Team2Guys/B-C pull request #308
Opened 2024-12-26 13:05 UTC by Wajid-Fareed

2024-12-26 13:09 UTC, MFaad1 commented on src/app/blinds/[product]/[subproduct]/page.tsx
> +  ]);
we don't need promise.all method

2024-12-26 13:19 UTC, MFaad1 requested changes

2024-12-26 13:19 UTC, MFaad1 commented on src/app/blog/[name]/Blog.tsx
> +    queryFn: fetchBlogs,
We shouldn't call the api's on client side as we are using parent server component

2024-12-26 13:19 UTC, MFaad1 commented on src/app/blog/[name]/Blog.tsx
> +            //@ts-expect-error
We should fix it rather than adding expected-error

2024-12-26 13:19 UTC, MFaad1 commented on src/app/blog/page.tsx
> +export async function generateMetadata(): Promise<Metadata> {
We should add meta data object rather than generateMetadata functions

2024-12-27 05:05 UTC, Wajid-Fareed commented on src/app/blinds/[product]/[subproduct]/page.tsx
> +  ]);
fixed

2024-12-27 05:05 UTC, Wajid-Fareed commented on src/app/blog/[name]/Blog.tsx
> +    queryFn: fetchBlogs,
fixed

2024-12-27 05:05 UTC, Wajid-Fareed commented on src/app/blog/[name]/Blog.tsx
> +            //@ts-expect-error
fixed

2024-12-27 05:05 UTC, Wajid-Fareed commented on src/app/blog/page.tsx
> +export async function generateMetadata(): Promise<Metadata> {
fixed

2024-12-27 06:09 UTC, MFaad1 approved these changes

2024-12-27 06:10 UTC, merged